// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPX79n-VBhfr-4MBBP4cDYwmofW99Oklw',
    appId: '1:1048031330014:web:f516adb16277f5aca10c4f',
    messagingSenderId: '1048031330014',
    projectId: 'calendar-data-a096b',
    authDomain: 'calendar-data-a096b.firebaseapp.com',
    storageBucket: 'calendar-data-a096b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhr6W-7bpKQd-cAkvo-5mwFVIUW2feAYI',
    appId: '1:1048031330014:android:86ad87418bfe314ba10c4f',
    messagingSenderId: '1048031330014',
    projectId: 'calendar-data-a096b',
    storageBucket: 'calendar-data-a096b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGa0-0ZjJkXpfMzfWN5BLD0prBvyKQaM',
    appId: '1:1048031330014:ios:16fbe11c48056c55a10c4f',
    messagingSenderId: '1048031330014',
    projectId: 'calendar-data-a096b',
    storageBucket: 'calendar-data-a096b.appspot.com',
    iosClientId: '1048031330014-4f8vm9b5u6v01pp4df9hqejoj5m7tsd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.calenderDataGmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGa0-0ZjJkXpfMzfWN5BLD0prBvyKQaM',
    appId: '1:1048031330014:ios:16fbe11c48056c55a10c4f',
    messagingSenderId: '1048031330014',
    projectId: 'calendar-data-a096b',
    storageBucket: 'calendar-data-a096b.appspot.com',
    iosClientId: '1048031330014-4f8vm9b5u6v01pp4df9hqejoj5m7tsd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.calenderDataGmail',
  );
}
